language: node_js
node_js:
  - "6.10.0"

sudo: true

notifications:
  email: true

branches:
  only:
    - master
    - develop

install:
  - npm install
  - npm test

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@4.3.0
  - npm install -g cordova ionic
  - npm install -g karma
